sudo: required

git:
  depth: 3
  quiet: true
  
addons:
  apt:
    package:
      - lcov

matrix:
  include:
    - os: linux
      language: cpp
      compiler: gcc
      script: ./scripts/build_linux_debug.sh
      name: "Linux | Debug"
    - os: osx
      language: cpp
      osx_image: xcode11.2
      compiler: clang
      script: ./scripts/build_macos.sh
      name: "macos | Debug"
    - os: osx
      language: cpp
      osx_image: xcode11.2
      compiler: clang
      script: ./scripts/build_ios.sh
      name: "iOS | debug"
    - os: linux
      language: android
      compiler: clang
      android:
        components:
          - tools
          - build-tools
          - platform-tools
          - android-21
        licenses:
          - 'android-sdk-preview-license-.+'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'
      before_script:
        - sudo apt-get remove cmake
        - echo yes | sdkmanager "ndk-bundle"
        - echo yes | sdkmanager "cmake;3.10.2.4988404"
        - export ANDROID_NDK=$ANDROID_HOME/ndk-bundle
        - export PATH=/usr/local/android-sdk/cmake/3.10.2.4988404/bin/:$PATH
      script:
        - ./scripts/build_android.sh
      name: "Linux | Android"      
    - os: linux
      compiler: clang
      arch: arm64
      script:
        - ./scripts/build_aarch64_linux.sh
      after_success:
        - lcov --directory . --capture --output-file coverage.info
        - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
        - lcov --list coverage.info
        - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
      name: "Linux | Arm64"
